name: online-alignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - numpy>=1.20.0
  - numba>=0.56.0
  - scipy>=0.16
  - pip
  - pip:
      # Install package in editable mode
      - -e .
